-- 🧾 1️⃣ Find 2nd Highest Salary
SELECT SALARY 
FROM EMPLOYEES 
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES) 
ORDER BY SALARY DESC 
LIMIT 1;


-- 🧾 2️⃣ Find Nth Highest Salary (Example: 4th Highest)
SELECT SALARY 
FROM EMPLOYEES  
ORDER BY SALARY DESC 
LIMIT 1 OFFSET 3;


-- 🧾 3️⃣ Remove Duplicate Rows (Keep One Record)
ALTER TABLE employees ADD id INT AUTO_INCREMENT PRIMARY KEY;

SET SQL_SAFE_UPDATES = 0;

WITH CTE AS (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY EMP_ID) AS RN 
    FROM EMPLOYEES
)
DELETE FROM EMPLOYEES 
WHERE (EMP_ID, ID) IN (
    SELECT EMP_ID, ID 
    FROM CTE 
    WHERE RN > 1
);

SELECT * FROM EMPLOYEES;


-- 🧾 4️⃣ Find Employees with Same Salary
SELECT SALARY, COUNT(DISTINCT EMP_ID) AS CNT 
FROM EMPLOYEES 
WHERE SALARY IS NOT NULL 
GROUP BY SALARY 
HAVING COUNT(DISTINCT EMP_ID) > 1;


-- 🧾 5️⃣ Get Last Record per Department (Latest Hire)
WITH CTE AS (
    SELECT DEPARTMENT, EMP_NAME, SALARY, HIRE_DATE,
           ROW_NUMBER() OVER (
               PARTITION BY DEPARTMENT 
               ORDER BY HIRE_DATE DESC
           ) AS RN
    FROM EMPLOYEES
)
SELECT * 
FROM CTE 
WHERE RN = 1;


-- 🧾 6️⃣ Find Missing IDs / Gaps in Sequence
WITH CTE AS (
    SELECT EMP_ID,
           LEAD(EMP_ID) OVER (ORDER BY EMP_ID) AS NEXT_ID
    FROM EMPLOYEES
)
SELECT EMP_ID + 1 AS MISSING_ID
FROM CTE
WHERE NEXT_ID - EMP_ID > 1;


-- 🧾 7️⃣ Count Occurrences (Department-wise)
SELECT DEPARTMENT, COUNT(*) AS CNT 
FROM EMPLOYEES 
GROUP BY DEPARTMENT;


-- 🧾 8️⃣ Top 3 Salaries per Department
WITH CTE AS (
    SELECT DEPARTMENT, SALARY,
           DENSE_RANK() OVER (
               PARTITION BY DEPARTMENT 
               ORDER BY SALARY DESC
           ) AS RNK,
           ROW_NUMBER() OVER (
               PARTITION BY DEPARTMENT, SALARY
           ) AS RN
    FROM EMPLOYEES
)
SELECT DEPARTMENT, SALARY 
FROM CTE 
WHERE RNK <= 3 AND RN = 1
ORDER BY DEPARTMENT, SALARY DESC;
